# Header

menu:
  主页: /
  相冊: /instagram

# SubNav
subnav:
  github: "https://github.com/Raysmond"
  weibo: "http://weibo.com/leijiankun"
  # rss: "#"
  # zhihu: "#"
  #douban: "#"
  mail: "mailto:i@raysmond.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-34658010-1'
favicon: /favicon.png

#你的头像url
avatar: http://tva3.sinaimg.cn/crop.0.0.750.750.180/69f4eca0jw8fa118uqadsj20ku0kuab0.jpg

#是否开启分享
share_jia: false
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: raysmond

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '文章列表'
  tagcloud: '標籤'
  # friends: '友链'
  aboutme: '關於我'

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

aboutme: Raysmond<br><br>九一摩羯，生性矛盾<br>熱愛運動，追求自我<br>混跡魔都，卖碼為生
